package com.khai.admin.constants;

public enum NOTIFICATION_TYPE {
    ORDER_001, //ORDER SUCCESS
    ORDER_002, // ORDER FAIL
    PROMOTION_001, // NEW PROMOTION
    SHOP_001 // NEW PRODUCT BY USER FOLLOWING
}
